# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e4d5136e7f36f919b8362252bb402dd74c7a916f2111c43d6a03dae151007207379126e17a40a18a3b500dbb151bb5bedf632748d1e4d03ce0435e00c1546ce
  account_sid:  <%= ENV["ACCOUNT_SID"] %> # Your Test Account SID from www.twilio.com/console/settings
  auth_token:  <%= ENV["AUTH_TOKEN"] %>
  sender: <%= ENV["SENDER"] %>
  address: <%= ENV["ADDRESS"] %>
  port: <%= ENV["PORT"] %>
  email: <%= ENV["EMAIL"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
test:
  secret_key_base: e404d4b728b148072acdb6bf61c33663274bab87b849553865c360472e22527292108cfb7df9aabfd28a5413129c7bdf28d36d84663c141b43f05f5078b5496c
  account_sid:  <%= ENV["ACCOUNT_SID"] %> # Your Test Account SID from www.twilio.com/console/settings
  auth_token:  <%= ENV["AUTH_TOKEN"] %>
  sender: <%= ENV["SENDER"] %>
  address: <%= ENV["ADDRESS"] %>
  port: <%= ENV["PORT"] %>
  email: <%= ENV["EMAIL"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  account_sid:  <%= ENV["ACCOUNT_SID"] %> # Your Test Account SID from www.twilio.com/console/settings
  auth_token:  <%= ENV["AUTH_TOKEN"] %>
  sender: <%= ENV["SENDER"] %>
  address: <%= ENV["ADDRESS"] %>
  port: <%= ENV["PORT"] %>
  email: <%= ENV["EMAIL"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>

